title: vegvisir
email: vikingfr@gmail.com
description: Hacking include sharing. This place dump stuffs I found interesting, maybe it can be helpful for others.
tagline: Explore, Understand, Hack, Share
baseurl: "/"
root: /
url: "https://v1k1ngfr.github.io/"
author: Viking
twitter_username: vikingfr
github_username:  v1k1ngfr
logo: "/assets/icones/logo.png"
social:
    name: Viking
    links:
        - https://github.com/v1k1ngfr/
        - https://twitter.com/vikingfr
lang: en_US

# Build settings
markdown: kramdown

paginate: 8
paginate_path: "page/:num"
github:
  repo:
    "https://github.com/v1k1ngfr/v1k1ngfr.github.io"
version: 1.1.0
plugins:
  - jekyll-paginate
  - jekyll-archives
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-redirect-from

excerpt_separator: <!--more-->
